try {
    fallibleFunction();
}
catch(ex) {
    console.error("It failed :(");
    console.error(ex);
}
